name: ukbb_deep_pretrain
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=11.8
  - numpy>=1.26.0
  - scipy>=1.14.0
  - antspyx>=0.5.0
  - antspynet>=0.2.0
  - matplotlib
  - notebook
  - ipywidgets
  - pip
  - pip:
    - nibabel  # for reading .nii.gz files
    - hd-bet
    - tqdm
