datasets:
  IXI:
    root: "data/IXI/mni_reg"
  OASIS_3:
    root: "data/OASIS_3/mni_reg"

data:
  unified_csv: "data/unified_data.csv"

model:
  checkpoint_path: "brain_age/run_20190719_00_epoch_best_mae.p"

fine_tune:
  batch_size: 8
  num_workers: 16
  lr_max: 3.e-3
  lr_min: 1.e-5
  weight_decay: 0.0005
  max_epochs: 50
  patience: 10
  ckpt_dir: "./checkpoints"

evaluation:
  batch_size: 8
  num_workers: 16
  output_dir: "results"
  # ckpt_path: "checkpoints/unfreeze_head_and_conv/ckpt_ep25.pth"
  ckpt_path: "brain_age/run_20190719_00_epoch_best_mae.p"
